@startuml

title 6 players END example

Uno *-- DrawPile
Uno *-- DiscardPile
Uno *-- "6" Player

WinnerPlayer -u-|> Player
WinnerPlayer  *-- "0" Card
LoserPlayer -u-|> Player
LoserPlayer "5" *-- "1..*" Card

DrawPile *-- "1..*" Card
DiscardPile *-- "1..*" Card

@enduml