@startuml

Title 6 players BEFORE PLAY (deck details) example

Uno *-- DrawPile
Uno *-- DiscardPile
Uno *-- "6" Player
Uno *-- Turn

Player *-- "0" Card

DiscardPile *-- "0" Card

NumeredCard --|> Card
ActionCard --|> Card

WildCard --|> Card
DrawFourWildCard --|> WildCard
SimpleWildCard --|> WildCard

DrawTwoCard --|> ActionCard
SkipCard --|> ActionCard
ReverseCard --|> ActionCard

DrawPile ..> "(0..9 + 1..9) * Card Color" NumeredCard
DrawPile ..> "2 * Card Color" DrawTwoCard
DrawPile ..> "2 * Card Color" ReverseCard
DrawPile ..> "2 * Card Color" SkipCard
DrawPile ..> "4" SimpleWildCard
DrawPile ..> "4" DrawFourWildCard
 
@enduml