@startuml

Uno *-- DrawPile
Uno *-- DiscardPile
Uno *-- "6" Player

note left of Uno : 6 players END example

WinnerPlayer -u-|> Player
WinnerPlayer *-- "0" Card
LoserPlayer -u-|> Player
LoserPlayer *-- "1..*" Card

DrawPile *-- Card
DiscardPile *-- "1..*" Card
@enduml