@startuml

Title 6 players BEFORE PLAY example

Uno *-- DrawPile
Uno *-- DiscardPile
Uno *-- "6" Player
Uno *-- Turn

Turn *-- "6" Player
Player *-- "0" Card

DrawPile *-- "108" Card
DiscardPile *-- "0" Card

@enduml