@startuml

Uno *-- DrawPile
Uno *-- DiscardPile
Uno *-- "6" Player
Uno *-- Turn

note left of Uno : 6 players PRESTART example

Turn *-- "6" Player
Turn *-- Direction

Turn ..> Clockwise : "starts on"

Clockwise --|> Direction
CounterClockwise --|> Direction


Player *-- "7" Card

DrawPile *-- "108 - 6 * 7" Card
DiscardPile *-- "0" Card
 
@enduml