@startuml
'https://plantuml.com/component-diagram
skinparam componentStyle uml1

package "Innermost circle" #Business{
    [Domain]
}

package "Inner circle" #Implementation {
    [Application] -u-> [Domain]  
    InputBoundary - [Application]
    [Application] -- OutputBoundary
    [Application] -- Gateway
}

package "Outer circle" #Technology {
    [Controllers] --> InputBoundary
}

package "Outer circle " #Technology {
    [Presenters] --|> OutputBoundary
    View -u- Presenters
}

package "Outer circle  " #Technology {
    [DAO] --|> Gateway
    [DAO] -- Repository
}

package "Outermost circle " #Application {
    [Database] -u-|> Repository
}

package "Outermost circle" #Application {
    [ViewImplementation] -u-|> View
}
@enduml