@startuml
'https://plantuml.com/component-diagram
skinparam componentStyle uml1

package "Entities" #Business{
    [Domain]
}

package "Use cases" #Implementation {
    [Application] -u-> [Domain]  
    InputBoundary - [Application]
    [Application] -- OutputBoundary
    [Application] -- Gateway
}

package "Adapters" #Technology {
    [Controllers] --> InputBoundary
}

package "Adapters " #Technology {
    [Presenters] --|> OutputBoundary
    View -u- Presenters
}

package "Adapters  " #Technology {
    [DAO] --|> Gateway
    [DAO] -- Repository
}

package "Frameworks " #Application {
    [Database] -u-|> Repository
}

package "Frameworks" #Application {
    [ViewImplementation] -u-|> View
}
@enduml