@startuml

Title 3 players BEFORE PLAY (deck details) example


object Uno {
}

object Player1{
    cards = [];
}

object Player2{
    cards = [];
}

object Player3{
    cards = [];
}

object DiscardPile{
    cards = [];
}

object DrawPile{
    cards = [allCards];
}

object NumeredCard0{
    number = 0;
    color = red;
}

object NumeredCard1{
    number = 1;
    color = blue;
}

object NumeredCard9{
    number = 9;
    color = green;
}

object SkipCard{
    color = blue;
}

object ReverseCard {
    color = blue;
}

object DrawTwoCard{
    color = red;

}

object SimpleWildCard{
}

object DrawFourWildCard{
}


note as Just4
    4
endnote

note as 1ForColor
    (* 4)
endnote

note as 2CopiesByColor
    (*2 * 4)
endnote

note as 1to9NumeredNote
    (1..9) * 2 * 4
endnote

Uno *-- DrawPile
Uno *-- DiscardPile
Uno *-- Player1
Uno *-- Player2
Uno *-- Player3

DrawPile ..>  NumeredCard0
DrawPile ..>  NumeredCard1
DrawPile ..>  NumeredCard9
DrawPile ..> SkipCard
DrawPile ..> ReverseCard
DrawPile ..> DrawTwoCard
DrawPile ..> SimpleWildCard
DrawPile ..> DrawFourWildCard

NumeredCard0 .. 1ForColor

1to9NumeredNote .r. NumeredCard1
1to9NumeredNote .l. NumeredCard9

SkipCard .. 2CopiesByColor
ReverseCard .. 2CopiesByColor
DrawTwoCard .. 2CopiesByColor

SimpleWildCard .. Just4
DrawFourWildCard .. Just4

 
@enduml