@startuml
title "States"

state BeforePlay
state InGame
state AfterPlay
state Finish

state c <<choice>>

[*] --> BeforePlay
BeforePlay --> InGame : "begin"

InGame --> c : "play a card"

c --> InGame : [nobody wins]
c --> AfterPlay : [somebody wins]

state e <<choice>>
AfterPlay --> e 

e --> BeforePlay : [restart]
e --> Finish : [no restart]

@enduml
